//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorPhotos
    {
        public int CompetitorPhotoID { get; set; }
        public string PhotoText { get; set; }
        public string PhotoURL { get; set; }
        public string CompetitorsID { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    }
}
