//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitors
    {
        public int CompetitorsID { get; set; }
        public string CompetitorNickname { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public string NumberOfVotes { get; set; }
        public string CarNumber { get; set; }
        public string Phone { get; set; }
        public string Model { get; set; }
        public string Address { get; set; }
        public string PhotographerName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DiveSite { get; set; }
        public string Location { get; set; }
        public string PhotographerComment { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    }
}
