//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitions
    {
        public int CompetitionID { get; set; }
        public string CompetitionTitle { get; set; }
        public string CompetitionFileName { get; set; }
        public System.DateTime StartRegisterDate { get; set; }
        public System.DateTime EndRegisterDate { get; set; }
        public System.DateTime StartVotingDate { get; set; }
        public System.DateTime EndVotingDate { get; set; }
        public System.DateTime CompetitionShowWinnerDate { get; set; }
        public string Body { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> Status { get; set; }
        public string EndMsg { get; set; }
        public string AfterVoteMsg { get; set; }
        public string AdminPercent { get; set; }
        public string WinnerDescription { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    }
}
