//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsArticles
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> ArticleDate { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TitleLink { get; set; }
        public Nullable<bool> DisplayLink { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PriceWithDiscount { get; set; }
        public string SalePriceDesc { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<int> FormID { get; set; }
        public string FormLinkTitle { get; set; }
        public string ArticleAuthor { get; set; }
        public Nullable<bool> DiaplaySummaryAtArticle { get; set; }
        public Nullable<bool> EnableQuantity { get; set; }
        public string FullImg { get; set; }
        public Nullable<bool> DisplayFullImgAsIs { get; set; }
        public string FullImgCaption { get; set; }
        public Nullable<bool> DisplayFullImgCaption { get; set; }
        public Nullable<bool> AutoFullImgCaption { get; set; }
        public string MainImg { get; set; }
        public Nullable<bool> DisplayMainImgAsIs { get; set; }
        public string MainImgCaption { get; set; }
        public Nullable<bool> DisplayMainImgCaption { get; set; }
        public Nullable<bool> AutoMainImgCaption { get; set; }
        public string MainImgSmall { get; set; }
        public string ListImgCaption { get; set; }
        public Nullable<bool> DisplayListImgAsIs { get; set; }
        public Nullable<bool> CreateMainImgSmall { get; set; }
        public Nullable<bool> AutoListImgCaption { get; set; }
        public Nullable<bool> DisplayListImgCaption { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DisplayDate { get; set; }
        public Nullable<System.DateTime> DisplayEndDate { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public Nullable<bool> TitleInH1Tag { get; set; }
        public string CatalogNumber { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    }
}
