//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsCategories
    {
        public dbsCategories()
        {
            this.dbsPhotoGallery = new HashSet<dbsPhotoGallery>();
            this.dbsSearch = new HashSet<dbsSearch>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryTitle { get; set; }
        public string CategoryShortDesc { get; set; }
        public string CategoryDesc { get; set; }
        public long TemplateID { get; set; }
        public Nullable<int> TemplateConfig { get; set; }
        public int ParentID { get; set; }
        public Nullable<int> CategoryLevel { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDivisionCat { get; set; }
        public Nullable<bool> HideChilds { get; set; }
        public string CategoryURL { get; set; }
        public Nullable<bool> NewWin { get; set; }
        public string MoreTitle { get; set; }
        public string EmailTitle { get; set; }
        public Nullable<long> LangID { get; set; }
        public string PageSize { get; set; }
        public Nullable<bool> EnableShoppingChart { get; set; }
        public Nullable<bool> EnableResponses { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> GUIID { get; set; }
        public string SystemPage { get; set; }
        public Nullable<bool> EnableTicker { get; set; }
        public Nullable<bool> EnableQuickSurvey { get; set; }
        public Nullable<bool> IsRootCategory { get; set; }
        public string TickerTitle { get; set; }
        public string QuickSurveyTitle { get; set; }
        public string CategoryImgName { get; set; }
        public string AttachedFile { get; set; }
        public Nullable<int> SourceCatDisplay { get; set; }
        public Nullable<int> OrderField { get; set; }
        public Nullable<bool> EnableMedia { get; set; }
        public Nullable<bool> EnableFreeBox { get; set; }
        public Nullable<int> AutoSelectionType { get; set; }
        public Nullable<int> AutoSelectionQuantity { get; set; }
        public Nullable<bool> RandomAutoSelection { get; set; }
        public Nullable<bool> CreateRSSChannel { get; set; }
        public string NettingCode { get; set; }
        public Nullable<bool> SSLRequired { get; set; }
        public string AbsoluteOrder { get; set; }
        public string FullTitle { get; set; }
        public Nullable<bool> TitleInH1Tag { get; set; }
        public Nullable<int> NewWinWidth { get; set; }
        public Nullable<int> NewWinHeight { get; set; }
        public Nullable<bool> PrintBreadcrumbs { get; set; }
        public Nullable<bool> EnableSearch { get; set; }
        public Nullable<bool> DisableDirectLink { get; set; }
        public Nullable<bool> EnableRatings { get; set; }
        public Nullable<bool> IsHorizontalCat { get; set; }
        public Nullable<bool> EnableComparison { get; set; }
        public Nullable<byte> Discount { get; set; }
        public Nullable<bool> EnableParams { get; set; }
        public Nullable<bool> EnableSocial { get; set; }
        public int UserID { get; set; }
    
        public virtual dbsTemplates dbsTemplates { get; set; }
        public virtual ICollection<dbsPhotoGallery> dbsPhotoGallery { get; set; }
        public virtual ICollection<dbsSearch> dbsSearch { get; set; }
    }
}
