//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsEvents_dbsCategories
    {
        public int EventID { get; set; }
        public int HorizontalCatID { get; set; }
        public Nullable<int> OrderNo { get; set; }
    }
}
