//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsExtraImg
    {
        public int ExtraImgID { get; set; }
        public int ModuleKey { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string FileName { get; set; }
        public int UserID { get; set; }
    }
}
