//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsEvents
    {
        public int EventID { get; set; }
        public string EventTitle { get; set; }
        public string TitleLink { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> DiaplaySummaryAtArticle { get; set; }
        public string Body { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public System.DateTime EventEndDate { get; set; }
        public string FormLinkTitle { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> TitleInH1Tag { get; set; }
        public Nullable<bool> DisplayInArch { get; set; }
        public string EventConclusion { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public string Location { get; set; }
        public string Organizer { get; set; }
        public string OrganizerWWW { get; set; }
        public string EventWWW { get; set; }
        public string ExternalSubsrWWW { get; set; }
        public Nullable<bool> FormAsInfo { get; set; }
        public Nullable<bool> SummaryAsInfo { get; set; }
        public Nullable<bool> LocationAsInfo { get; set; }
        public Nullable<bool> OrganizerAsInfo { get; set; }
        public Nullable<bool> EventWWWAsInfo { get; set; }
        public Nullable<bool> ExternalSubsrWWWAsInfo { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    }
}
