//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsPhotoGallery
    {
        public int ItemID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string MainImg { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string MainImgSmall { get; set; }
        public string FullImg { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> PrintTitle { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int UserID { get; set; }
    
        public virtual dbsCategories dbsCategories { get; set; }
    }
}
