//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsSearch
    {
        public long ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string SystemPg { get; set; }
        public Nullable<int> SourceCategoryID { get; set; }
        public Nullable<bool> AutoKeyWords { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual dbsCategories dbsCategories { get; set; }
    }
}
