//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsTemplatesTrans
    {
        public long SourceTemplateID { get; set; }
        public long TargetTemplateID { get; set; }
    
        public virtual dbsTemplates dbsTemplates { get; set; }
    }
}
