//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsTemplates
    {
        public dbsTemplates()
        {
            this.dbsCategories = new HashSet<dbsCategories>();
            this.dbsTemplatesTrans = new HashSet<dbsTemplatesTrans>();
        }
    
        public long TemplateID { get; set; }
        public string TemplateTitle { get; set; }
        public string TemplateTitleEng { get; set; }
        public string AdminPage { get; set; }
        public string SiteIndexPage { get; set; }
        public string SiteItemPage { get; set; }
        public string TemplateTblName { get; set; }
        public string TblIndexKey { get; set; }
        public string TblTitleKey { get; set; }
        public bool IsMultiple { get; set; }
        public int IsActiveTemplate { get; set; }
        public bool Searchable { get; set; }
        public string AutoImportIdentifier { get; set; }
        public string RSSChannelPage { get; set; }
        public int UserID { get; set; }
        public Nullable<long> UniqueID { get; set; }
    
        public virtual ICollection<dbsCategories> dbsCategories { get; set; }
        public virtual ICollection<dbsTemplatesTrans> dbsTemplatesTrans { get; set; }
    }
}
