//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesGallery
    {
        public int ImageID { get; set; }
        public string ImageTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string ImgFileName { get; set; }
        public string SourceURL { get; set; }
        public string CaptionFileName { get; set; }
        public string CaptionURL { get; set; }
        public Nullable<int> SourceWidth { get; set; }
        public Nullable<int> SourceHeight { get; set; }
        public Nullable<bool> HiddenMedia { get; set; }
        public int UserID { get; set; }
    
        public virtual ImageGallerySubjects ImageGallerySubjects { get; set; }
    }
}
