//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageGallerySubjects
    {
        public ImageGallerySubjects()
        {
            this.ImagesGallery = new HashSet<ImagesGallery>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectTitle { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<ImagesGallery> ImagesGallery { get; set; }
    }
}
