//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.OldDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldDB : DbContext
    {
        public OldDB()
            : base("name=OldDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competitions> Competitions { get; set; }
        public virtual DbSet<CompetitorPhotos> CompetitorPhotos { get; set; }
        public virtual DbSet<Competitors> Competitors { get; set; }
        public virtual DbSet<CompetitorVotes> CompetitorVotes { get; set; }
        public virtual DbSet<dbsArticles> dbsArticles { get; set; }
        public virtual DbSet<dbsArticlesAttached> dbsArticlesAttached { get; set; }
        public virtual DbSet<dbsCategories> dbsCategories { get; set; }
        public virtual DbSet<dbsEvents> dbsEvents { get; set; }
        public virtual DbSet<dbsExtraImg> dbsExtraImg { get; set; }
        public virtual DbSet<dbsPhotoGallery> dbsPhotoGallery { get; set; }
        public virtual DbSet<dbsSearch> dbsSearch { get; set; }
        public virtual DbSet<dbsTemplates> dbsTemplates { get; set; }
        public virtual DbSet<dbsTemplatesTrans> dbsTemplatesTrans { get; set; }
        public virtual DbSet<ImageGallerySubjects> ImageGallerySubjects { get; set; }
        public virtual DbSet<ImagesGallery> ImagesGallery { get; set; }
        public virtual DbSet<MetaTags> MetaTags { get; set; }
        public virtual DbSet<dbsEvents_dbsCategories> dbsEvents_dbsCategories { get; set; }
    }
}
