//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uco.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uco.Models.Resources.DataModels", typeof(DataModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth - Day.
        /// </summary>
        public static string BirthDateDay {
            get {
                return ResourceManager.GetString("BirthDateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth - Month.
        /// </summary>
        public static string BirthDateMonth {
            get {
                return ResourceManager.GetString("BirthDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday - Year.
        /// </summary>
        public static string BirthDateYear {
            get {
                return ResourceManager.GetString("BirthDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a city.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        public static string CustomerAddressRequired {
            get {
                return ResourceManager.GetString("CustomerAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diver Level.
        /// </summary>
        public static string DivingRank {
            get {
                return ResourceManager.GetString("DivingRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Level Diver.
        /// </summary>
        public static string DivingRankRequired {
            get {
                return ResourceManager.GetString("DivingRankRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string Healthy {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID number.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an ID number of 9 digits.
        /// </summary>
        public static string IdNumberLimit9 {
            get {
                return ResourceManager.GetString("IdNumberLimit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID number.
        /// </summary>
        public static string IdNumberRequired {
            get {
                return ResourceManager.GetString("IdNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Start Date.
        /// </summary>
        public static string InsuranceDate {
            get {
                return ResourceManager.GetString("InsuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Date - Day.
        /// </summary>
        public static string InsuranceDateDay {
            get {
                return ResourceManager.GetString("InsuranceDateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Start Date - Month.
        /// </summary>
        public static string InsuranceDateMonth {
            get {
                return ResourceManager.GetString("InsuranceDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Start Date - Year.
        /// </summary>
        public static string InsuranceDateYear {
            get {
                return ResourceManager.GetString("InsuranceDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string InsuranceGenderFemale {
            get {
                return ResourceManager.GetString("InsuranceGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string InsuranceGenderMale {
            get {
                return ResourceManager.GetString("InsuranceGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string InsuranceGenderNone {
            get {
                return ResourceManager.GetString("InsuranceGenderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal.
        /// </summary>
        public static string IsRenew {
            get {
                return ResourceManager.GetString("IsRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        public static string Magazine {
            get {
                return ResourceManager.GetString("Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine Article.
        /// </summary>
        public static string MagazineArticle {
            get {
                return ResourceManager.GetString("MagazineArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string Magazines {
            get {
                return ResourceManager.GetString("Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the proper structure of e-mail.
        /// </summary>
        public static string MailCorrect {
            get {
                return ResourceManager.GetString("MailCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        public static string MailRequired {
            get {
                return ResourceManager.GetString("MailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Telephone in a proper structure, for example: 0501234567.
        /// </summary>
        public static string PhoneCorrect {
            get {
                return ResourceManager.GetString("PhoneCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a phone number.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnant.
        /// </summary>
        public static string Pregnant {
            get {
                return ResourceManager.GetString("Pregnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        public static string SearchInsuranceDateYear {
            get {
                return ResourceManager.GetString("SearchInsuranceDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנס שנת לידה בארבע ספרות.
        /// </summary>
        public static string SearchInsuranceDateYearLimit4 {
            get {
                return ResourceManager.GetString("SearchInsuranceDateYearLimit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Year of birth.
        /// </summary>
        public static string SearchInsuranceDateYearRequired {
            get {
                return ResourceManager.GetString("SearchInsuranceDateYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreeing to the terms of the policy.
        /// </summary>
        public static string Takanon {
            get {
                return ResourceManager.GetString("Takanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Insurance.
        /// </summary>
        public static string TravelInsurancePeriods {
            get {
                return ResourceManager.GetString("TravelInsurancePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Type.
        /// </summary>
        public static string TravelInsurancePeriodsRequired {
            get {
                return ResourceManager.GetString("TravelInsurancePeriodsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew first name.
        /// </summary>
        public static string UserFname {
            get {
                return ResourceManager.GetString("UserFname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English First name.
        /// </summary>
        public static string UserFnameEng {
            get {
                return ResourceManager.GetString("UserFnameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter English First name.
        /// </summary>
        public static string UserFnameEngRequired {
            get {
                return ResourceManager.GetString("UserFnameEngRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name in Hebrew.
        /// </summary>
        public static string UserFnameRequired {
            get {
                return ResourceManager.GetString("UserFnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew family name.
        /// </summary>
        public static string UserLname {
            get {
                return ResourceManager.GetString("UserLname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English first name.
        /// </summary>
        public static string UserLnameEng {
            get {
                return ResourceManager.GetString("UserLnameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter English name.
        /// </summary>
        public static string UserLnameEngRequired {
            get {
                return ResourceManager.GetString("UserLnameEngRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name in Hebrew.
        /// </summary>
        public static string UserLnameRequired {
            get {
                return ResourceManager.GetString("UserLnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
