//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uco.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uco.Models.Resources.SystemModels", typeof(SystemModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email Required.
        /// </summary>
        public static string AdminEmailRequired {
            get {
                return ResourceManager.GetString("AdminEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article list page.
        /// </summary>
        public static string ArticleListPage {
            get {
                return ResourceManager.GetString("ArticleListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article page.
        /// </summary>
        public static string ArticlePage {
            get {
                return ResourceManager.GetString("ArticlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha required.
        /// </summary>
        public static string CaptchaRequired {
            get {
                return ResourceManager.GetString("CaptchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change time.
        /// </summary>
        public static string ChangeTime {
            get {
                return ResourceManager.GetString("ChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityRequired.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password compare.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Contact number {ID} from {HTTP_HOST}&lt;/h1&gt; 
        ///Name: {ContactName} &lt;br /&gt;
        ///Email: {ContactEmail} &lt;br /&gt;
        ///Phone: {ContactPhone} &lt;br /&gt;
        ///Data: {ContactData} &lt;br /&gt;
        ///Referal: {ContactReferal} &lt;br /&gt;
        ///Url: {ContactUrl}.
        /// </summary>
        public static string ContactMailBody {
            get {
                return ResourceManager.GetString("ContactMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number {ID} from {HTTP_HOST}.
        /// </summary>
        public static string ContactMailSubject {
            get {
                return ResourceManager.GetString("ContactMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content page.
        /// </summary>
        public static string ContentPage {
            get {
                return ResourceManager.GetString("ContentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminator.
        /// </summary>
        public static string Discriminator {
            get {
                return ResourceManager.GetString("Discriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailBody.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email mesage.
        /// </summary>
        public static string EmailMesage {
            get {
                return ResourceManager.GetString("EmailMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email subject.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended From.
        /// </summary>
        public static string ExtendedFrom {
            get {
                return ResourceManager.GetString("ExtendedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended To.
        /// </summary>
        public static string ExtendedTo {
            get {
                return ResourceManager.GetString("ExtendedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password answer attempt count.
        /// </summary>
        public static string FailedPasswordAnswerAttemptCount {
            get {
                return ResourceManager.GetString("FailedPasswordAnswerAttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password answer attempt window start.
        /// </summary>
        public static string FailedPasswordAnswerAttemptWindowStart {
            get {
                return ResourceManager.GetString("FailedPasswordAnswerAttemptWindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password attempt count.
        /// </summary>
        public static string FailedPasswordAttemptCount {
            get {
                return ResourceManager.GetString("FailedPasswordAttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password attempt window start.
        /// </summary>
        public static string FailedPasswordAttemptWindowStart {
            get {
                return ResourceManager.GetString("FailedPasswordAttemptWindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form page.
        /// </summary>
        public static string FormPage {
            get {
                return ResourceManager.GetString("FormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormTextAfter.
        /// </summary>
        public static string FormTextAfter {
            get {
                return ResourceManager.GetString("FormTextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent back.
        /// </summary>
        public static string FormTextEmail {
            get {
                return ResourceManager.GetString("FormTextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FotterHtml.
        /// </summary>
        public static string FotterHtml {
            get {
                return ResourceManager.GetString("FotterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery page.
        /// </summary>
        public static string GalleryPage {
            get {
                return ResourceManager.GetString("GalleryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeaderHtml.
        /// </summary>
        public static string HeaderHtml {
            get {
                return ResourceManager.GetString("HeaderHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible captcha.
        /// </summary>
        public static string InvisibleCaptcha {
            get {
                return ResourceManager.GetString("InvisibleCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is locked out.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is online.
        /// </summary>
        public static string IsOnline {
            get {
                return ResourceManager.GetString("IsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSystem.
        /// </summary>
        public static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item1.
        /// </summary>
        public static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item2.
        /// </summary>
        public static string Item2 {
            get {
                return ResourceManager.GetString("Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item3.
        /// </summary>
        public static string Item3 {
            get {
                return ResourceManager.GetString("Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangCode.
        /// </summary>
        public static string LangCode {
            get {
                return ResourceManager.GetString("LangCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language page.
        /// </summary>
        public static string LanguagePage {
            get {
                return ResourceManager.GetString("LanguagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL.
        /// </summary>
        public static string LanguageRTL {
            get {
                return ResourceManager.GetString("LanguageRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity date.
        /// </summary>
        public static string LastActivityDate {
            get {
                return ResourceManager.GetString("LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last lockedout date.
        /// </summary>
        public static string LastLockedOutDate {
            get {
                return ResourceManager.GetString("LastLockedOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login date.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last password changed date.
        /// </summary>
        public static string LastPasswordChangedDate {
            get {
                return ResourceManager.GetString("LastPasswordChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last try.
        /// </summary>
        public static string LastTry {
            get {
                return ResourceManager.GetString("LastTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine article page.
        /// </summary>
        public static string MagazineArticlePage {
            get {
                return ResourceManager.GetString("MagazineArticlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine page.
        /// </summary>
        public static string MagazinePage {
            get {
                return ResourceManager.GetString("MagazinePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines page.
        /// </summary>
        public static string MagazinesPage {
            get {
                return ResourceManager.GetString("MagazinesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail recipients.
        /// </summary>
        public static string MailRecipients {
            get {
                return ResourceManager.GetString("MailRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailTo.
        /// </summary>
        public static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu permissions.
        /// </summary>
        public static string MenuPermissions {
            get {
                return ResourceManager.GetString("MenuPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileTab.
        /// </summary>
        public static string MobileTab {
            get {
                return ResourceManager.GetString("MobileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music File.
        /// </summary>
        public static string MusicFile {
            get {
                return ResourceManager.GetString("MusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music File Type.
        /// </summary>
        public static string MusicFileType {
            get {
                return ResourceManager.GetString("MusicFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Required.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept terms.
        /// </summary>
        public static string NewsletterAccept {
            get {
                return ResourceManager.GetString("NewsletterAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept terms mandatory.
        /// </summary>
        public static string NewsletterAcceptMandatory {
            get {
                return ResourceManager.GetString("NewsletterAcceptMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterData.
        /// </summary>
        public static string NewsletterData {
            get {
                return ResourceManager.GetString("NewsletterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterDataRequired.
        /// </summary>
        public static string NewsletterDataRequired {
            get {
                return ResourceManager.GetString("NewsletterDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterDate.
        /// </summary>
        public static string NewsletterDate {
            get {
                return ResourceManager.GetString("NewsletterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterDateRequired.
        /// </summary>
        public static string NewsletterDateRequired {
            get {
                return ResourceManager.GetString("NewsletterDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterEmail.
        /// </summary>
        public static string NewsletterEmail {
            get {
                return ResourceManager.GetString("NewsletterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Valid Email Address.
        /// </summary>
        public static string NewsletterMailNotValid {
            get {
                return ResourceManager.GetString("NewsletterMailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterName.
        /// </summary>
        public static string NewsletterName {
            get {
                return ResourceManager.GetString("NewsletterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsletterNameRequired.
        /// </summary>
        public static string NewsletterNameRequired {
            get {
                return ResourceManager.GetString("NewsletterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News list page.
        /// </summary>
        public static string NewsListPage {
            get {
                return ResourceManager.GetString("NewsListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News page.
        /// </summary>
        public static string NewsPage {
            get {
                return ResourceManager.GetString("NewsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password Required.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page404.
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page500.
        /// </summary>
        public static string Page500 {
            get {
                return ResourceManager.GetString("Page500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageLogin.
        /// </summary>
        public static string PageLogin {
            get {
                return ResourceManager.GetString("PageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSitemap.
        /// </summary>
        public static string PageSitemap {
            get {
                return ResourceManager.GetString("PageSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID.
        /// </summary>
        public static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID Required.
        /// </summary>
        public static string ParentIDRequired {
            get {
                return ResourceManager.GetString("ParentIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordAnswer.
        /// </summary>
        public static string PasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - הסיסמה חייבת להיות בעלת {2} תווים לפחות.
        /// </summary>
        public static string PasswordMinimumLength {
            get {
                return ResourceManager.GetString("PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Question.
        /// </summary>
        public static string PasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Edit.
        /// </summary>
        public static string PermissionsEdit {
            get {
                return ResourceManager.GetString("PermissionsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update child pages.
        /// </summary>
        public static string PermissionsUpdateChildPages {
            get {
                return ResourceManager.GetString("PermissionsUpdateChildPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions View.
        /// </summary>
        public static string PermissionsView {
            get {
                return ResourceManager.GetString("PermissionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Not Valid.
        /// </summary>
        public static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicalPath.
        /// </summary>
        public static string PhysicalPath {
            get {
                return ResourceManager.GetString("PhysicalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Pic {
            get {
                return ResourceManager.GetString("Pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileMenuImage.
        /// </summary>
        public static string PicMobile {
            get {
                return ResourceManager.GetString("PicMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect page.
        /// </summary>
        public static string RedirectPage {
            get {
                return ResourceManager.GetString("RedirectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect To.
        /// </summary>
        public static string RedirectTo {
            get {
                return ResourceManager.GetString("RedirectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referal.
        /// </summary>
        public static string Referal {
            get {
                return ResourceManager.GetString("Referal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredTitle.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role.
        /// </summary>
        public static string RoleDefault {
            get {
                return ResourceManager.GetString("RoleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesRequired.
        /// </summary>
        public static string RolesRequired {
            get {
                return ResourceManager.GetString("RolesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchCategoryData.
        /// </summary>
        public static string SearchCategoryData {
            get {
                return ResourceManager.GetString("SearchCategoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchCategoryIDs.
        /// </summary>
        public static string SearchCategoryIDs {
            get {
                return ResourceManager.GetString("SearchCategoryIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Category Names.
        /// </summary>
        public static string SearchCategoryNames {
            get {
                return ResourceManager.GetString("SearchCategoryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo.
        /// </summary>
        public static string Seo {
            get {
                return ResourceManager.GetString("Seo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1.
        /// </summary>
        public static string SeoH1 {
            get {
                return ResourceManager.GetString("SeoH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoInLinkName.
        /// </summary>
        public static string SeoInLinkName {
            get {
                return ResourceManager.GetString("SeoInLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kywords.
        /// </summary>
        public static string SeoKywords {
            get {
                return ResourceManager.GetString("SeoKywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Name.
        /// </summary>
        public static string SeoUrlName {
            get {
                return ResourceManager.GetString("SeoUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoUrlNameError.
        /// </summary>
        public static string SeoUrlNameError {
            get {
                return ResourceManager.GetString("SeoUrlNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescriptionRequired.
        /// </summary>
        public static string ShortDescriptionRequired {
            get {
                return ResourceManager.GetString("ShortDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowChildrensAsTableOnly.
        /// </summary>
        public static string ShowChildrensAsTableOnly {
            get {
                return ResourceManager.GetString("ShowChildrensAsTableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowInMenu.
        /// </summary>
        public static string ShowInMenu {
            get {
                return ResourceManager.GetString("ShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowOnMobileMenu.
        /// </summary>
        public static string ShowInMobileMenu {
            get {
                return ResourceManager.GetString("ShowInMobileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowInSitemap.
        /// </summary>
        public static string ShowInSitemap {
            get {
                return ResourceManager.GetString("ShowInSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap page.
        /// </summary>
        public static string SiteMapPage {
            get {
                return ResourceManager.GetString("SiteMapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemName.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TabCategory {
            get {
                return ResourceManager.GetString("TabCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string TabContent {
            get {
                return ResourceManager.GetString("TabContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string TabData {
            get {
                return ResourceManager.GetString("TabData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string TabDomain {
            get {
                return ResourceManager.GetString("TabDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extedned Insurance.
        /// </summary>
        public static string TabExtedned {
            get {
                return ResourceManager.GetString("TabExtedned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string TabPermissions {
            get {
                return ResourceManager.GetString("TabPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string TabRoles {
            get {
                return ResourceManager.GetString("TabRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo.
        /// </summary>
        public static string TabSeo {
            get {
                return ResourceManager.GetString("TabSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text after.
        /// </summary>
        public static string TabTextAfter {
            get {
                return ResourceManager.GetString("TabTextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetSite.
        /// </summary>
        public static string TargetSite {
            get {
                return ResourceManager.GetString("TargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimesSent.
        /// </summary>
        public static string TimesSent {
            get {
                return ResourceManager.GetString("TimesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleRequired.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Insurance List Page.
        /// </summary>
        public static string TravelInsurancePeriodListPage {
            get {
                return ResourceManager.GetString("TravelInsurancePeriodListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Insurance Page.
        /// </summary>
        public static string TravelInsurancePeriodPage {
            get {
                return ResourceManager.GetString("TravelInsurancePeriodPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlReferrer.
        /// </summary>
        public static string UrlReferrer {
            get {
                return ResourceManager.GetString("UrlReferrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAgent.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCity.
        /// </summary>
        public static string UserCity {
            get {
                return ResourceManager.GetString("UserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserEmail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserEmail Required.
        /// </summary>
        public static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstName.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstName Required.
        /// </summary>
        public static string UserFirstNameRequired {
            get {
                return ResourceManager.GetString("UserFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserHostAddress.
        /// </summary>
        public static string UserHostAddress {
            get {
                return ResourceManager.GetString("UserHostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLastName.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLastName Required.
        /// </summary>
        public static string UserLastNameRequired {
            get {
                return ResourceManager.GetString("UserLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Captcha.
        /// </summary>
        public static string ValidateCaptcha {
            get {
                return ResourceManager.GetString("ValidateCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Invisible Captcha.
        /// </summary>
        public static string ValidateInvisibleCaptcha {
            get {
                return ResourceManager.GetString("ValidateInvisibleCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value1.
        /// </summary>
        public static string Value1 {
            get {
                return ResourceManager.GetString("Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value2.
        /// </summary>
        public static string Value2 {
            get {
                return ResourceManager.GetString("Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value3.
        /// </summary>
        public static string Value3 {
            get {
                return ResourceManager.GetString("Value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer Email.
        /// </summary>
        public static string WriterEmail {
            get {
                return ResourceManager.GetString("WriterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write rName.
        /// </summary>
        public static string WriterName {
            get {
                return ResourceManager.GetString("WriterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriterNameRequired.
        /// </summary>
        public static string WriterNameRequired {
            get {
                return ResourceManager.GetString("WriterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer Pic.
        /// </summary>
        public static string WriterPic {
            get {
                return ResourceManager.GetString("WriterPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriterPicRequired.
        /// </summary>
        public static string WriterPicRequired {
            get {
                return ResourceManager.GetString("WriterPicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer Short Description.
        /// </summary>
        public static string WriterShortDescription {
            get {
                return ResourceManager.GetString("WriterShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriterShortDescriptionRequired.
        /// </summary>
        public static string WriterShortDescriptionRequired {
            get {
                return ResourceManager.GetString("WriterShortDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer Site.
        /// </summary>
        public static string WriterSite {
            get {
                return ResourceManager.GetString("WriterSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLGrid.
        /// </summary>
        public static string XMLGrid {
            get {
                return ResourceManager.GetString("XMLGrid", resourceCulture);
            }
        }
    }
}
