#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uco.Migrate
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iDive_HE_V1")]
	public partial class oldDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdbsCategory(dbsCategory instance);
    partial void UpdatedbsCategory(dbsCategory instance);
    partial void DeletedbsCategory(dbsCategory instance);
    partial void InsertdbsArticle(dbsArticle instance);
    partial void UpdatedbsArticle(dbsArticle instance);
    partial void DeletedbsArticle(dbsArticle instance);
    partial void InsertdbsArticles_dbsCategory(dbsArticles_dbsCategory instance);
    partial void UpdatedbsArticles_dbsCategory(dbsArticles_dbsCategory instance);
    partial void DeletedbsArticles_dbsCategory(dbsArticles_dbsCategory instance);
    #endregion
		
		public oldDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iDive_HE_V1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public oldDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oldDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oldDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oldDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dbsCategory> dbsCategories
		{
			get
			{
				return this.GetTable<dbsCategory>();
			}
		}
		
		public System.Data.Linq.Table<dbsArticle> dbsArticles
		{
			get
			{
				return this.GetTable<dbsArticle>();
			}
		}
		
		public System.Data.Linq.Table<dbsArticles_dbsCategory> dbsArticles_dbsCategories
		{
			get
			{
				return this.GetTable<dbsArticles_dbsCategory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dbsCategories")]
	public partial class dbsCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private string _CategoryTitle;
		
		private string _CategoryShortDesc;
		
		private string _CategoryDesc;
		
		private long _TemplateID;
		
		private System.Nullable<int> _TemplateConfig;
		
		private int _ParentID;
		
		private System.Nullable<int> _CategoryLevel;
		
		private System.Nullable<int> _OrderKey;
		
		private System.Nullable<bool> _IsLocked;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDivisionCat;
		
		private System.Nullable<bool> _HideChilds;
		
		private string _CategoryURL;
		
		private System.Nullable<bool> _NewWin;
		
		private string _MoreTitle;
		
		private string _EmailTitle;
		
		private System.Nullable<long> _LangID;
		
		private string _PageSize;
		
		private System.Nullable<bool> _EnableShoppingChart;
		
		private System.Nullable<bool> _EnableResponses;
		
		private System.Nullable<int> _FormID;
		
		private System.Nullable<int> _GUIID;
		
		private string _SystemPage;
		
		private System.Nullable<bool> _EnableTicker;
		
		private System.Nullable<bool> _EnableQuickSurvey;
		
		private System.Nullable<bool> _IsRootCategory;
		
		private string _TickerTitle;
		
		private string _QuickSurveyTitle;
		
		private string _CategoryImgName;
		
		private string _AttachedFile;
		
		private System.Nullable<int> _SourceCatDisplay;
		
		private System.Nullable<int> _OrderField;
		
		private System.Nullable<bool> _EnableMedia;
		
		private System.Nullable<bool> _EnableFreeBox;
		
		private System.Nullable<int> _AutoSelectionType;
		
		private System.Nullable<int> _AutoSelectionQuantity;
		
		private System.Nullable<bool> _RandomAutoSelection;
		
		private System.Nullable<bool> _CreateRSSChannel;
		
		private string _NettingCode;
		
		private System.Nullable<bool> _SSLRequired;
		
		private string _AbsoluteOrder;
		
		private string _FullTitle;
		
		private System.Nullable<bool> _TitleInH1Tag;
		
		private System.Nullable<int> _NewWinWidth;
		
		private System.Nullable<int> _NewWinHeight;
		
		private System.Nullable<bool> _PrintBreadcrumbs;
		
		private System.Nullable<bool> _EnableSearch;
		
		private System.Nullable<bool> _DisableDirectLink;
		
		private System.Nullable<bool> _EnableRatings;
		
		private System.Nullable<bool> _IsHorizontalCat;
		
		private System.Nullable<bool> _EnableComparison;
		
		private System.Nullable<byte> _Discount;
		
		private System.Nullable<bool> _EnableParams;
		
		private System.Nullable<bool> _EnableSocial;
		
		private int _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnCategoryTitleChanging(string value);
    partial void OnCategoryTitleChanged();
    partial void OnCategoryShortDescChanging(string value);
    partial void OnCategoryShortDescChanged();
    partial void OnCategoryDescChanging(string value);
    partial void OnCategoryDescChanged();
    partial void OnTemplateIDChanging(long value);
    partial void OnTemplateIDChanged();
    partial void OnTemplateConfigChanging(System.Nullable<int> value);
    partial void OnTemplateConfigChanged();
    partial void OnParentIDChanging(int value);
    partial void OnParentIDChanged();
    partial void OnCategoryLevelChanging(System.Nullable<int> value);
    partial void OnCategoryLevelChanged();
    partial void OnOrderKeyChanging(System.Nullable<int> value);
    partial void OnOrderKeyChanged();
    partial void OnIsLockedChanging(System.Nullable<bool> value);
    partial void OnIsLockedChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnIsDivisionCatChanging(System.Nullable<bool> value);
    partial void OnIsDivisionCatChanged();
    partial void OnHideChildsChanging(System.Nullable<bool> value);
    partial void OnHideChildsChanged();
    partial void OnCategoryURLChanging(string value);
    partial void OnCategoryURLChanged();
    partial void OnNewWinChanging(System.Nullable<bool> value);
    partial void OnNewWinChanged();
    partial void OnMoreTitleChanging(string value);
    partial void OnMoreTitleChanged();
    partial void OnEmailTitleChanging(string value);
    partial void OnEmailTitleChanged();
    partial void OnLangIDChanging(System.Nullable<long> value);
    partial void OnLangIDChanged();
    partial void OnPageSizeChanging(string value);
    partial void OnPageSizeChanged();
    partial void OnEnableShoppingChartChanging(System.Nullable<bool> value);
    partial void OnEnableShoppingChartChanged();
    partial void OnEnableResponsesChanging(System.Nullable<bool> value);
    partial void OnEnableResponsesChanged();
    partial void OnFormIDChanging(System.Nullable<int> value);
    partial void OnFormIDChanged();
    partial void OnGUIIDChanging(System.Nullable<int> value);
    partial void OnGUIIDChanged();
    partial void OnSystemPageChanging(string value);
    partial void OnSystemPageChanged();
    partial void OnEnableTickerChanging(System.Nullable<bool> value);
    partial void OnEnableTickerChanged();
    partial void OnEnableQuickSurveyChanging(System.Nullable<bool> value);
    partial void OnEnableQuickSurveyChanged();
    partial void OnIsRootCategoryChanging(System.Nullable<bool> value);
    partial void OnIsRootCategoryChanged();
    partial void OnTickerTitleChanging(string value);
    partial void OnTickerTitleChanged();
    partial void OnQuickSurveyTitleChanging(string value);
    partial void OnQuickSurveyTitleChanged();
    partial void OnCategoryImgNameChanging(string value);
    partial void OnCategoryImgNameChanged();
    partial void OnAttachedFileChanging(string value);
    partial void OnAttachedFileChanged();
    partial void OnSourceCatDisplayChanging(System.Nullable<int> value);
    partial void OnSourceCatDisplayChanged();
    partial void OnOrderFieldChanging(System.Nullable<int> value);
    partial void OnOrderFieldChanged();
    partial void OnEnableMediaChanging(System.Nullable<bool> value);
    partial void OnEnableMediaChanged();
    partial void OnEnableFreeBoxChanging(System.Nullable<bool> value);
    partial void OnEnableFreeBoxChanged();
    partial void OnAutoSelectionTypeChanging(System.Nullable<int> value);
    partial void OnAutoSelectionTypeChanged();
    partial void OnAutoSelectionQuantityChanging(System.Nullable<int> value);
    partial void OnAutoSelectionQuantityChanged();
    partial void OnRandomAutoSelectionChanging(System.Nullable<bool> value);
    partial void OnRandomAutoSelectionChanged();
    partial void OnCreateRSSChannelChanging(System.Nullable<bool> value);
    partial void OnCreateRSSChannelChanged();
    partial void OnNettingCodeChanging(string value);
    partial void OnNettingCodeChanged();
    partial void OnSSLRequiredChanging(System.Nullable<bool> value);
    partial void OnSSLRequiredChanged();
    partial void OnAbsoluteOrderChanging(string value);
    partial void OnAbsoluteOrderChanged();
    partial void OnFullTitleChanging(string value);
    partial void OnFullTitleChanged();
    partial void OnTitleInH1TagChanging(System.Nullable<bool> value);
    partial void OnTitleInH1TagChanged();
    partial void OnNewWinWidthChanging(System.Nullable<int> value);
    partial void OnNewWinWidthChanged();
    partial void OnNewWinHeightChanging(System.Nullable<int> value);
    partial void OnNewWinHeightChanged();
    partial void OnPrintBreadcrumbsChanging(System.Nullable<bool> value);
    partial void OnPrintBreadcrumbsChanged();
    partial void OnEnableSearchChanging(System.Nullable<bool> value);
    partial void OnEnableSearchChanged();
    partial void OnDisableDirectLinkChanging(System.Nullable<bool> value);
    partial void OnDisableDirectLinkChanged();
    partial void OnEnableRatingsChanging(System.Nullable<bool> value);
    partial void OnEnableRatingsChanged();
    partial void OnIsHorizontalCatChanging(System.Nullable<bool> value);
    partial void OnIsHorizontalCatChanged();
    partial void OnEnableComparisonChanging(System.Nullable<bool> value);
    partial void OnEnableComparisonChanged();
    partial void OnDiscountChanging(System.Nullable<byte> value);
    partial void OnDiscountChanged();
    partial void OnEnableParamsChanging(System.Nullable<bool> value);
    partial void OnEnableParamsChanged();
    partial void OnEnableSocialChanging(System.Nullable<bool> value);
    partial void OnEnableSocialChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public dbsCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTitle", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string CategoryTitle
		{
			get
			{
				return this._CategoryTitle;
			}
			set
			{
				if ((this._CategoryTitle != value))
				{
					this.OnCategoryTitleChanging(value);
					this.SendPropertyChanging();
					this._CategoryTitle = value;
					this.SendPropertyChanged("CategoryTitle");
					this.OnCategoryTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryShortDesc", DbType="NVarChar(2000)")]
		public string CategoryShortDesc
		{
			get
			{
				return this._CategoryShortDesc;
			}
			set
			{
				if ((this._CategoryShortDesc != value))
				{
					this.OnCategoryShortDescChanging(value);
					this.SendPropertyChanging();
					this._CategoryShortDesc = value;
					this.SendPropertyChanged("CategoryShortDesc");
					this.OnCategoryShortDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CategoryDesc
		{
			get
			{
				return this._CategoryDesc;
			}
			set
			{
				if ((this._CategoryDesc != value))
				{
					this.OnCategoryDescChanging(value);
					this.SendPropertyChanging();
					this._CategoryDesc = value;
					this.SendPropertyChanged("CategoryDesc");
					this.OnCategoryDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateID", DbType="BigInt NOT NULL")]
		public long TemplateID
		{
			get
			{
				return this._TemplateID;
			}
			set
			{
				if ((this._TemplateID != value))
				{
					this.OnTemplateIDChanging(value);
					this.SendPropertyChanging();
					this._TemplateID = value;
					this.SendPropertyChanged("TemplateID");
					this.OnTemplateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateConfig", DbType="Int")]
		public System.Nullable<int> TemplateConfig
		{
			get
			{
				return this._TemplateConfig;
			}
			set
			{
				if ((this._TemplateConfig != value))
				{
					this.OnTemplateConfigChanging(value);
					this.SendPropertyChanging();
					this._TemplateConfig = value;
					this.SendPropertyChanged("TemplateConfig");
					this.OnTemplateConfigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryLevel", DbType="Int")]
		public System.Nullable<int> CategoryLevel
		{
			get
			{
				return this._CategoryLevel;
			}
			set
			{
				if ((this._CategoryLevel != value))
				{
					this.OnCategoryLevelChanging(value);
					this.SendPropertyChanging();
					this._CategoryLevel = value;
					this.SendPropertyChanged("CategoryLevel");
					this.OnCategoryLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="Int")]
		public System.Nullable<int> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit")]
		public System.Nullable<bool> IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDivisionCat", DbType="Bit")]
		public System.Nullable<bool> IsDivisionCat
		{
			get
			{
				return this._IsDivisionCat;
			}
			set
			{
				if ((this._IsDivisionCat != value))
				{
					this.OnIsDivisionCatChanging(value);
					this.SendPropertyChanging();
					this._IsDivisionCat = value;
					this.SendPropertyChanged("IsDivisionCat");
					this.OnIsDivisionCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HideChilds", DbType="Bit")]
		public System.Nullable<bool> HideChilds
		{
			get
			{
				return this._HideChilds;
			}
			set
			{
				if ((this._HideChilds != value))
				{
					this.OnHideChildsChanging(value);
					this.SendPropertyChanging();
					this._HideChilds = value;
					this.SendPropertyChanged("HideChilds");
					this.OnHideChildsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryURL", DbType="VarChar(300)")]
		public string CategoryURL
		{
			get
			{
				return this._CategoryURL;
			}
			set
			{
				if ((this._CategoryURL != value))
				{
					this.OnCategoryURLChanging(value);
					this.SendPropertyChanging();
					this._CategoryURL = value;
					this.SendPropertyChanged("CategoryURL");
					this.OnCategoryURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWin", DbType="Bit")]
		public System.Nullable<bool> NewWin
		{
			get
			{
				return this._NewWin;
			}
			set
			{
				if ((this._NewWin != value))
				{
					this.OnNewWinChanging(value);
					this.SendPropertyChanging();
					this._NewWin = value;
					this.SendPropertyChanged("NewWin");
					this.OnNewWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreTitle", DbType="NVarChar(100)")]
		public string MoreTitle
		{
			get
			{
				return this._MoreTitle;
			}
			set
			{
				if ((this._MoreTitle != value))
				{
					this.OnMoreTitleChanging(value);
					this.SendPropertyChanging();
					this._MoreTitle = value;
					this.SendPropertyChanged("MoreTitle");
					this.OnMoreTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTitle", DbType="NVarChar(100)")]
		public string EmailTitle
		{
			get
			{
				return this._EmailTitle;
			}
			set
			{
				if ((this._EmailTitle != value))
				{
					this.OnEmailTitleChanging(value);
					this.SendPropertyChanging();
					this._EmailTitle = value;
					this.SendPropertyChanged("EmailTitle");
					this.OnEmailTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LangID", DbType="BigInt")]
		public System.Nullable<long> LangID
		{
			get
			{
				return this._LangID;
			}
			set
			{
				if ((this._LangID != value))
				{
					this.OnLangIDChanging(value);
					this.SendPropertyChanging();
					this._LangID = value;
					this.SendPropertyChanged("LangID");
					this.OnLangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageSize", DbType="VarChar(10)")]
		public string PageSize
		{
			get
			{
				return this._PageSize;
			}
			set
			{
				if ((this._PageSize != value))
				{
					this.OnPageSizeChanging(value);
					this.SendPropertyChanging();
					this._PageSize = value;
					this.SendPropertyChanged("PageSize");
					this.OnPageSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableShoppingChart", DbType="Bit")]
		public System.Nullable<bool> EnableShoppingChart
		{
			get
			{
				return this._EnableShoppingChart;
			}
			set
			{
				if ((this._EnableShoppingChart != value))
				{
					this.OnEnableShoppingChartChanging(value);
					this.SendPropertyChanging();
					this._EnableShoppingChart = value;
					this.SendPropertyChanged("EnableShoppingChart");
					this.OnEnableShoppingChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableResponses", DbType="Bit")]
		public System.Nullable<bool> EnableResponses
		{
			get
			{
				return this._EnableResponses;
			}
			set
			{
				if ((this._EnableResponses != value))
				{
					this.OnEnableResponsesChanging(value);
					this.SendPropertyChanging();
					this._EnableResponses = value;
					this.SendPropertyChanged("EnableResponses");
					this.OnEnableResponsesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int")]
		public System.Nullable<int> FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUIID", DbType="Int")]
		public System.Nullable<int> GUIID
		{
			get
			{
				return this._GUIID;
			}
			set
			{
				if ((this._GUIID != value))
				{
					this.OnGUIIDChanging(value);
					this.SendPropertyChanging();
					this._GUIID = value;
					this.SendPropertyChanged("GUIID");
					this.OnGUIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemPage", DbType="VarChar(50)")]
		public string SystemPage
		{
			get
			{
				return this._SystemPage;
			}
			set
			{
				if ((this._SystemPage != value))
				{
					this.OnSystemPageChanging(value);
					this.SendPropertyChanging();
					this._SystemPage = value;
					this.SendPropertyChanged("SystemPage");
					this.OnSystemPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableTicker", DbType="Bit")]
		public System.Nullable<bool> EnableTicker
		{
			get
			{
				return this._EnableTicker;
			}
			set
			{
				if ((this._EnableTicker != value))
				{
					this.OnEnableTickerChanging(value);
					this.SendPropertyChanging();
					this._EnableTicker = value;
					this.SendPropertyChanged("EnableTicker");
					this.OnEnableTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableQuickSurvey", DbType="Bit")]
		public System.Nullable<bool> EnableQuickSurvey
		{
			get
			{
				return this._EnableQuickSurvey;
			}
			set
			{
				if ((this._EnableQuickSurvey != value))
				{
					this.OnEnableQuickSurveyChanging(value);
					this.SendPropertyChanging();
					this._EnableQuickSurvey = value;
					this.SendPropertyChanged("EnableQuickSurvey");
					this.OnEnableQuickSurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRootCategory", DbType="Bit")]
		public System.Nullable<bool> IsRootCategory
		{
			get
			{
				return this._IsRootCategory;
			}
			set
			{
				if ((this._IsRootCategory != value))
				{
					this.OnIsRootCategoryChanging(value);
					this.SendPropertyChanging();
					this._IsRootCategory = value;
					this.SendPropertyChanged("IsRootCategory");
					this.OnIsRootCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TickerTitle", DbType="NVarChar(50)")]
		public string TickerTitle
		{
			get
			{
				return this._TickerTitle;
			}
			set
			{
				if ((this._TickerTitle != value))
				{
					this.OnTickerTitleChanging(value);
					this.SendPropertyChanging();
					this._TickerTitle = value;
					this.SendPropertyChanged("TickerTitle");
					this.OnTickerTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuickSurveyTitle", DbType="NVarChar(50)")]
		public string QuickSurveyTitle
		{
			get
			{
				return this._QuickSurveyTitle;
			}
			set
			{
				if ((this._QuickSurveyTitle != value))
				{
					this.OnQuickSurveyTitleChanging(value);
					this.SendPropertyChanging();
					this._QuickSurveyTitle = value;
					this.SendPropertyChanged("QuickSurveyTitle");
					this.OnQuickSurveyTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryImgName", DbType="NVarChar(50)")]
		public string CategoryImgName
		{
			get
			{
				return this._CategoryImgName;
			}
			set
			{
				if ((this._CategoryImgName != value))
				{
					this.OnCategoryImgNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryImgName = value;
					this.SendPropertyChanged("CategoryImgName");
					this.OnCategoryImgNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachedFile", DbType="NVarChar(50)")]
		public string AttachedFile
		{
			get
			{
				return this._AttachedFile;
			}
			set
			{
				if ((this._AttachedFile != value))
				{
					this.OnAttachedFileChanging(value);
					this.SendPropertyChanging();
					this._AttachedFile = value;
					this.SendPropertyChanged("AttachedFile");
					this.OnAttachedFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceCatDisplay", DbType="Int")]
		public System.Nullable<int> SourceCatDisplay
		{
			get
			{
				return this._SourceCatDisplay;
			}
			set
			{
				if ((this._SourceCatDisplay != value))
				{
					this.OnSourceCatDisplayChanging(value);
					this.SendPropertyChanging();
					this._SourceCatDisplay = value;
					this.SendPropertyChanged("SourceCatDisplay");
					this.OnSourceCatDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderField", DbType="Int")]
		public System.Nullable<int> OrderField
		{
			get
			{
				return this._OrderField;
			}
			set
			{
				if ((this._OrderField != value))
				{
					this.OnOrderFieldChanging(value);
					this.SendPropertyChanging();
					this._OrderField = value;
					this.SendPropertyChanged("OrderField");
					this.OnOrderFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableMedia", DbType="Bit")]
		public System.Nullable<bool> EnableMedia
		{
			get
			{
				return this._EnableMedia;
			}
			set
			{
				if ((this._EnableMedia != value))
				{
					this.OnEnableMediaChanging(value);
					this.SendPropertyChanging();
					this._EnableMedia = value;
					this.SendPropertyChanged("EnableMedia");
					this.OnEnableMediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableFreeBox", DbType="Bit")]
		public System.Nullable<bool> EnableFreeBox
		{
			get
			{
				return this._EnableFreeBox;
			}
			set
			{
				if ((this._EnableFreeBox != value))
				{
					this.OnEnableFreeBoxChanging(value);
					this.SendPropertyChanging();
					this._EnableFreeBox = value;
					this.SendPropertyChanged("EnableFreeBox");
					this.OnEnableFreeBoxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoSelectionType", DbType="Int")]
		public System.Nullable<int> AutoSelectionType
		{
			get
			{
				return this._AutoSelectionType;
			}
			set
			{
				if ((this._AutoSelectionType != value))
				{
					this.OnAutoSelectionTypeChanging(value);
					this.SendPropertyChanging();
					this._AutoSelectionType = value;
					this.SendPropertyChanged("AutoSelectionType");
					this.OnAutoSelectionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoSelectionQuantity", DbType="Int")]
		public System.Nullable<int> AutoSelectionQuantity
		{
			get
			{
				return this._AutoSelectionQuantity;
			}
			set
			{
				if ((this._AutoSelectionQuantity != value))
				{
					this.OnAutoSelectionQuantityChanging(value);
					this.SendPropertyChanging();
					this._AutoSelectionQuantity = value;
					this.SendPropertyChanged("AutoSelectionQuantity");
					this.OnAutoSelectionQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandomAutoSelection", DbType="Bit")]
		public System.Nullable<bool> RandomAutoSelection
		{
			get
			{
				return this._RandomAutoSelection;
			}
			set
			{
				if ((this._RandomAutoSelection != value))
				{
					this.OnRandomAutoSelectionChanging(value);
					this.SendPropertyChanging();
					this._RandomAutoSelection = value;
					this.SendPropertyChanged("RandomAutoSelection");
					this.OnRandomAutoSelectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateRSSChannel", DbType="Bit")]
		public System.Nullable<bool> CreateRSSChannel
		{
			get
			{
				return this._CreateRSSChannel;
			}
			set
			{
				if ((this._CreateRSSChannel != value))
				{
					this.OnCreateRSSChannelChanging(value);
					this.SendPropertyChanging();
					this._CreateRSSChannel = value;
					this.SendPropertyChanged("CreateRSSChannel");
					this.OnCreateRSSChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NettingCode", DbType="VarChar(20)")]
		public string NettingCode
		{
			get
			{
				return this._NettingCode;
			}
			set
			{
				if ((this._NettingCode != value))
				{
					this.OnNettingCodeChanging(value);
					this.SendPropertyChanging();
					this._NettingCode = value;
					this.SendPropertyChanged("NettingCode");
					this.OnNettingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSLRequired", DbType="Bit")]
		public System.Nullable<bool> SSLRequired
		{
			get
			{
				return this._SSLRequired;
			}
			set
			{
				if ((this._SSLRequired != value))
				{
					this.OnSSLRequiredChanging(value);
					this.SendPropertyChanging();
					this._SSLRequired = value;
					this.SendPropertyChanged("SSLRequired");
					this.OnSSLRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbsoluteOrder", DbType="VarChar(100)")]
		public string AbsoluteOrder
		{
			get
			{
				return this._AbsoluteOrder;
			}
			set
			{
				if ((this._AbsoluteOrder != value))
				{
					this.OnAbsoluteOrderChanging(value);
					this.SendPropertyChanging();
					this._AbsoluteOrder = value;
					this.SendPropertyChanged("AbsoluteOrder");
					this.OnAbsoluteOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullTitle", DbType="NVarChar(200)")]
		public string FullTitle
		{
			get
			{
				return this._FullTitle;
			}
			set
			{
				if ((this._FullTitle != value))
				{
					this.OnFullTitleChanging(value);
					this.SendPropertyChanging();
					this._FullTitle = value;
					this.SendPropertyChanged("FullTitle");
					this.OnFullTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleInH1Tag", DbType="Bit")]
		public System.Nullable<bool> TitleInH1Tag
		{
			get
			{
				return this._TitleInH1Tag;
			}
			set
			{
				if ((this._TitleInH1Tag != value))
				{
					this.OnTitleInH1TagChanging(value);
					this.SendPropertyChanging();
					this._TitleInH1Tag = value;
					this.SendPropertyChanged("TitleInH1Tag");
					this.OnTitleInH1TagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWinWidth", DbType="Int")]
		public System.Nullable<int> NewWinWidth
		{
			get
			{
				return this._NewWinWidth;
			}
			set
			{
				if ((this._NewWinWidth != value))
				{
					this.OnNewWinWidthChanging(value);
					this.SendPropertyChanging();
					this._NewWinWidth = value;
					this.SendPropertyChanged("NewWinWidth");
					this.OnNewWinWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWinHeight", DbType="Int")]
		public System.Nullable<int> NewWinHeight
		{
			get
			{
				return this._NewWinHeight;
			}
			set
			{
				if ((this._NewWinHeight != value))
				{
					this.OnNewWinHeightChanging(value);
					this.SendPropertyChanging();
					this._NewWinHeight = value;
					this.SendPropertyChanged("NewWinHeight");
					this.OnNewWinHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintBreadcrumbs", DbType="Bit")]
		public System.Nullable<bool> PrintBreadcrumbs
		{
			get
			{
				return this._PrintBreadcrumbs;
			}
			set
			{
				if ((this._PrintBreadcrumbs != value))
				{
					this.OnPrintBreadcrumbsChanging(value);
					this.SendPropertyChanging();
					this._PrintBreadcrumbs = value;
					this.SendPropertyChanged("PrintBreadcrumbs");
					this.OnPrintBreadcrumbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableSearch", DbType="Bit")]
		public System.Nullable<bool> EnableSearch
		{
			get
			{
				return this._EnableSearch;
			}
			set
			{
				if ((this._EnableSearch != value))
				{
					this.OnEnableSearchChanging(value);
					this.SendPropertyChanging();
					this._EnableSearch = value;
					this.SendPropertyChanged("EnableSearch");
					this.OnEnableSearchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisableDirectLink", DbType="Bit")]
		public System.Nullable<bool> DisableDirectLink
		{
			get
			{
				return this._DisableDirectLink;
			}
			set
			{
				if ((this._DisableDirectLink != value))
				{
					this.OnDisableDirectLinkChanging(value);
					this.SendPropertyChanging();
					this._DisableDirectLink = value;
					this.SendPropertyChanged("DisableDirectLink");
					this.OnDisableDirectLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableRatings", DbType="Bit")]
		public System.Nullable<bool> EnableRatings
		{
			get
			{
				return this._EnableRatings;
			}
			set
			{
				if ((this._EnableRatings != value))
				{
					this.OnEnableRatingsChanging(value);
					this.SendPropertyChanging();
					this._EnableRatings = value;
					this.SendPropertyChanged("EnableRatings");
					this.OnEnableRatingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHorizontalCat", DbType="Bit")]
		public System.Nullable<bool> IsHorizontalCat
		{
			get
			{
				return this._IsHorizontalCat;
			}
			set
			{
				if ((this._IsHorizontalCat != value))
				{
					this.OnIsHorizontalCatChanging(value);
					this.SendPropertyChanging();
					this._IsHorizontalCat = value;
					this.SendPropertyChanged("IsHorizontalCat");
					this.OnIsHorizontalCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableComparison", DbType="Bit")]
		public System.Nullable<bool> EnableComparison
		{
			get
			{
				return this._EnableComparison;
			}
			set
			{
				if ((this._EnableComparison != value))
				{
					this.OnEnableComparisonChanging(value);
					this.SendPropertyChanging();
					this._EnableComparison = value;
					this.SendPropertyChanged("EnableComparison");
					this.OnEnableComparisonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="TinyInt")]
		public System.Nullable<byte> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableParams", DbType="Bit")]
		public System.Nullable<bool> EnableParams
		{
			get
			{
				return this._EnableParams;
			}
			set
			{
				if ((this._EnableParams != value))
				{
					this.OnEnableParamsChanging(value);
					this.SendPropertyChanging();
					this._EnableParams = value;
					this.SendPropertyChanged("EnableParams");
					this.OnEnableParamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableSocial", DbType="Bit")]
		public System.Nullable<bool> EnableSocial
		{
			get
			{
				return this._EnableSocial;
			}
			set
			{
				if ((this._EnableSocial != value))
				{
					this.OnEnableSocialChanging(value);
					this.SendPropertyChanging();
					this._EnableSocial = value;
					this.SendPropertyChanged("EnableSocial");
					this.OnEnableSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dbsArticles")]
	public partial class dbsArticle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ArticleID;
		
		private string _Title;
		
		private string _Summary;
		
		private string _Body;
		
		private System.Nullable<System.DateTime> _ArticleDate;
		
		private System.Nullable<int> _CategoryID;
		
		private string _TitleLink;
		
		private System.Nullable<bool> _DisplayLink;
		
		private System.Nullable<decimal> _MarketPrice;
		
		private System.Nullable<decimal> _SalePrice;
		
		private System.Nullable<decimal> _PriceWithDiscount;
		
		private string _SalePriceDesc;
		
		private System.Nullable<decimal> _Weight;
		
		private System.Nullable<int> _SupplierID;
		
		private System.Nullable<decimal> _ShippingFee;
		
		private System.Nullable<int> _FormID;
		
		private string _FormLinkTitle;
		
		private string _ArticleAuthor;
		
		private System.Nullable<bool> _DiaplaySummaryAtArticle;
		
		private System.Nullable<bool> _EnableQuantity;
		
		private string _FullImg;
		
		private System.Nullable<bool> _DisplayFullImgAsIs;
		
		private string _FullImgCaption;
		
		private System.Nullable<bool> _DisplayFullImgCaption;
		
		private System.Nullable<bool> _AutoFullImgCaption;
		
		private string _MainImg;
		
		private System.Nullable<bool> _DisplayMainImgAsIs;
		
		private string _MainImgCaption;
		
		private System.Nullable<bool> _DisplayMainImgCaption;
		
		private System.Nullable<bool> _AutoMainImgCaption;
		
		private string _MainImgSmall;
		
		private string _ListImgCaption;
		
		private System.Nullable<bool> _DisplayListImgAsIs;
		
		private System.Nullable<bool> _CreateMainImgSmall;
		
		private System.Nullable<bool> _AutoListImgCaption;
		
		private System.Nullable<bool> _DisplayListImgCaption;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<System.DateTime> _DisplayDate;
		
		private System.Nullable<System.DateTime> _DisplayEndDate;
		
		private System.Nullable<int> _OrderKey;
		
		private System.Nullable<bool> _TitleInH1Tag;
		
		private string _CatalogNumber;
		
		private System.Nullable<System.DateTime> _LastUpdated;
		
		private int _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArticleIDChanging(int value);
    partial void OnArticleIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSummaryChanging(string value);
    partial void OnSummaryChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnArticleDateChanging(System.Nullable<System.DateTime> value);
    partial void OnArticleDateChanged();
    partial void OnCategoryIDChanging(System.Nullable<int> value);
    partial void OnCategoryIDChanged();
    partial void OnTitleLinkChanging(string value);
    partial void OnTitleLinkChanged();
    partial void OnDisplayLinkChanging(System.Nullable<bool> value);
    partial void OnDisplayLinkChanged();
    partial void OnMarketPriceChanging(System.Nullable<decimal> value);
    partial void OnMarketPriceChanged();
    partial void OnSalePriceChanging(System.Nullable<decimal> value);
    partial void OnSalePriceChanged();
    partial void OnPriceWithDiscountChanging(System.Nullable<decimal> value);
    partial void OnPriceWithDiscountChanged();
    partial void OnSalePriceDescChanging(string value);
    partial void OnSalePriceDescChanged();
    partial void OnWeightChanging(System.Nullable<decimal> value);
    partial void OnWeightChanged();
    partial void OnSupplierIDChanging(System.Nullable<int> value);
    partial void OnSupplierIDChanged();
    partial void OnShippingFeeChanging(System.Nullable<decimal> value);
    partial void OnShippingFeeChanged();
    partial void OnFormIDChanging(System.Nullable<int> value);
    partial void OnFormIDChanged();
    partial void OnFormLinkTitleChanging(string value);
    partial void OnFormLinkTitleChanged();
    partial void OnArticleAuthorChanging(string value);
    partial void OnArticleAuthorChanged();
    partial void OnDiaplaySummaryAtArticleChanging(System.Nullable<bool> value);
    partial void OnDiaplaySummaryAtArticleChanged();
    partial void OnEnableQuantityChanging(System.Nullable<bool> value);
    partial void OnEnableQuantityChanged();
    partial void OnFullImgChanging(string value);
    partial void OnFullImgChanged();
    partial void OnDisplayFullImgAsIsChanging(System.Nullable<bool> value);
    partial void OnDisplayFullImgAsIsChanged();
    partial void OnFullImgCaptionChanging(string value);
    partial void OnFullImgCaptionChanged();
    partial void OnDisplayFullImgCaptionChanging(System.Nullable<bool> value);
    partial void OnDisplayFullImgCaptionChanged();
    partial void OnAutoFullImgCaptionChanging(System.Nullable<bool> value);
    partial void OnAutoFullImgCaptionChanged();
    partial void OnMainImgChanging(string value);
    partial void OnMainImgChanged();
    partial void OnDisplayMainImgAsIsChanging(System.Nullable<bool> value);
    partial void OnDisplayMainImgAsIsChanged();
    partial void OnMainImgCaptionChanging(string value);
    partial void OnMainImgCaptionChanged();
    partial void OnDisplayMainImgCaptionChanging(System.Nullable<bool> value);
    partial void OnDisplayMainImgCaptionChanged();
    partial void OnAutoMainImgCaptionChanging(System.Nullable<bool> value);
    partial void OnAutoMainImgCaptionChanged();
    partial void OnMainImgSmallChanging(string value);
    partial void OnMainImgSmallChanged();
    partial void OnListImgCaptionChanging(string value);
    partial void OnListImgCaptionChanged();
    partial void OnDisplayListImgAsIsChanging(System.Nullable<bool> value);
    partial void OnDisplayListImgAsIsChanged();
    partial void OnCreateMainImgSmallChanging(System.Nullable<bool> value);
    partial void OnCreateMainImgSmallChanged();
    partial void OnAutoListImgCaptionChanging(System.Nullable<bool> value);
    partial void OnAutoListImgCaptionChanged();
    partial void OnDisplayListImgCaptionChanging(System.Nullable<bool> value);
    partial void OnDisplayListImgCaptionChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnDisplayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDisplayDateChanged();
    partial void OnDisplayEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDisplayEndDateChanged();
    partial void OnOrderKeyChanging(System.Nullable<int> value);
    partial void OnOrderKeyChanged();
    partial void OnTitleInH1TagChanging(System.Nullable<bool> value);
    partial void OnTitleInH1TagChanged();
    partial void OnCatalogNumberChanging(string value);
    partial void OnCatalogNumberChanged();
    partial void OnLastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdatedChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public dbsArticle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ArticleID
		{
			get
			{
				return this._ArticleID;
			}
			set
			{
				if ((this._ArticleID != value))
				{
					this.OnArticleIDChanging(value);
					this.SendPropertyChanging();
					this._ArticleID = value;
					this.SendPropertyChanged("ArticleID");
					this.OnArticleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(260) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="NVarChar(3000)")]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this.OnSummaryChanging(value);
					this.SendPropertyChanging();
					this._Summary = value;
					this.SendPropertyChanged("Summary");
					this.OnSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ArticleDate
		{
			get
			{
				return this._ArticleDate;
			}
			set
			{
				if ((this._ArticleDate != value))
				{
					this.OnArticleDateChanging(value);
					this.SendPropertyChanging();
					this._ArticleDate = value;
					this.SendPropertyChanged("ArticleDate");
					this.OnArticleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleLink", DbType="VarChar(140)")]
		public string TitleLink
		{
			get
			{
				return this._TitleLink;
			}
			set
			{
				if ((this._TitleLink != value))
				{
					this.OnTitleLinkChanging(value);
					this.SendPropertyChanging();
					this._TitleLink = value;
					this.SendPropertyChanged("TitleLink");
					this.OnTitleLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayLink", DbType="Bit")]
		public System.Nullable<bool> DisplayLink
		{
			get
			{
				return this._DisplayLink;
			}
			set
			{
				if ((this._DisplayLink != value))
				{
					this.OnDisplayLinkChanging(value);
					this.SendPropertyChanging();
					this._DisplayLink = value;
					this.SendPropertyChanged("DisplayLink");
					this.OnDisplayLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Money")]
		public System.Nullable<decimal> MarketPrice
		{
			get
			{
				return this._MarketPrice;
			}
			set
			{
				if ((this._MarketPrice != value))
				{
					this.OnMarketPriceChanging(value);
					this.SendPropertyChanging();
					this._MarketPrice = value;
					this.SendPropertyChanged("MarketPrice");
					this.OnMarketPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePrice", DbType="Money")]
		public System.Nullable<decimal> SalePrice
		{
			get
			{
				return this._SalePrice;
			}
			set
			{
				if ((this._SalePrice != value))
				{
					this.OnSalePriceChanging(value);
					this.SendPropertyChanging();
					this._SalePrice = value;
					this.SendPropertyChanged("SalePrice");
					this.OnSalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceWithDiscount", DbType="Money")]
		public System.Nullable<decimal> PriceWithDiscount
		{
			get
			{
				return this._PriceWithDiscount;
			}
			set
			{
				if ((this._PriceWithDiscount != value))
				{
					this.OnPriceWithDiscountChanging(value);
					this.SendPropertyChanging();
					this._PriceWithDiscount = value;
					this.SendPropertyChanged("PriceWithDiscount");
					this.OnPriceWithDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePriceDesc", DbType="NVarChar(20)")]
		public string SalePriceDesc
		{
			get
			{
				return this._SalePriceDesc;
			}
			set
			{
				if ((this._SalePriceDesc != value))
				{
					this.OnSalePriceDescChanging(value);
					this.SendPropertyChanging();
					this._SalePriceDesc = value;
					this.SendPropertyChanged("SalePriceDesc");
					this.OnSalePriceDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Money")]
		public System.Nullable<decimal> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int")]
		public System.Nullable<int> SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this.OnSupplierIDChanging(value);
					this.SendPropertyChanging();
					this._SupplierID = value;
					this.SendPropertyChanged("SupplierID");
					this.OnSupplierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingFee", DbType="Money")]
		public System.Nullable<decimal> ShippingFee
		{
			get
			{
				return this._ShippingFee;
			}
			set
			{
				if ((this._ShippingFee != value))
				{
					this.OnShippingFeeChanging(value);
					this.SendPropertyChanging();
					this._ShippingFee = value;
					this.SendPropertyChanged("ShippingFee");
					this.OnShippingFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Int")]
		public System.Nullable<int> FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormLinkTitle", DbType="NVarChar(50)")]
		public string FormLinkTitle
		{
			get
			{
				return this._FormLinkTitle;
			}
			set
			{
				if ((this._FormLinkTitle != value))
				{
					this.OnFormLinkTitleChanging(value);
					this.SendPropertyChanging();
					this._FormLinkTitle = value;
					this.SendPropertyChanged("FormLinkTitle");
					this.OnFormLinkTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleAuthor", DbType="NVarChar(100)")]
		public string ArticleAuthor
		{
			get
			{
				return this._ArticleAuthor;
			}
			set
			{
				if ((this._ArticleAuthor != value))
				{
					this.OnArticleAuthorChanging(value);
					this.SendPropertyChanging();
					this._ArticleAuthor = value;
					this.SendPropertyChanged("ArticleAuthor");
					this.OnArticleAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaplaySummaryAtArticle", DbType="Bit")]
		public System.Nullable<bool> DiaplaySummaryAtArticle
		{
			get
			{
				return this._DiaplaySummaryAtArticle;
			}
			set
			{
				if ((this._DiaplaySummaryAtArticle != value))
				{
					this.OnDiaplaySummaryAtArticleChanging(value);
					this.SendPropertyChanging();
					this._DiaplaySummaryAtArticle = value;
					this.SendPropertyChanged("DiaplaySummaryAtArticle");
					this.OnDiaplaySummaryAtArticleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableQuantity", DbType="Bit")]
		public System.Nullable<bool> EnableQuantity
		{
			get
			{
				return this._EnableQuantity;
			}
			set
			{
				if ((this._EnableQuantity != value))
				{
					this.OnEnableQuantityChanging(value);
					this.SendPropertyChanging();
					this._EnableQuantity = value;
					this.SendPropertyChanged("EnableQuantity");
					this.OnEnableQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullImg", DbType="NVarChar(100)")]
		public string FullImg
		{
			get
			{
				return this._FullImg;
			}
			set
			{
				if ((this._FullImg != value))
				{
					this.OnFullImgChanging(value);
					this.SendPropertyChanging();
					this._FullImg = value;
					this.SendPropertyChanged("FullImg");
					this.OnFullImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayFullImgAsIs", DbType="Bit")]
		public System.Nullable<bool> DisplayFullImgAsIs
		{
			get
			{
				return this._DisplayFullImgAsIs;
			}
			set
			{
				if ((this._DisplayFullImgAsIs != value))
				{
					this.OnDisplayFullImgAsIsChanging(value);
					this.SendPropertyChanging();
					this._DisplayFullImgAsIs = value;
					this.SendPropertyChanged("DisplayFullImgAsIs");
					this.OnDisplayFullImgAsIsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullImgCaption", DbType="NVarChar(50)")]
		public string FullImgCaption
		{
			get
			{
				return this._FullImgCaption;
			}
			set
			{
				if ((this._FullImgCaption != value))
				{
					this.OnFullImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._FullImgCaption = value;
					this.SendPropertyChanged("FullImgCaption");
					this.OnFullImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayFullImgCaption", DbType="Bit")]
		public System.Nullable<bool> DisplayFullImgCaption
		{
			get
			{
				return this._DisplayFullImgCaption;
			}
			set
			{
				if ((this._DisplayFullImgCaption != value))
				{
					this.OnDisplayFullImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._DisplayFullImgCaption = value;
					this.SendPropertyChanged("DisplayFullImgCaption");
					this.OnDisplayFullImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoFullImgCaption", DbType="Bit")]
		public System.Nullable<bool> AutoFullImgCaption
		{
			get
			{
				return this._AutoFullImgCaption;
			}
			set
			{
				if ((this._AutoFullImgCaption != value))
				{
					this.OnAutoFullImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._AutoFullImgCaption = value;
					this.SendPropertyChanged("AutoFullImgCaption");
					this.OnAutoFullImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainImg", DbType="NVarChar(100)")]
		public string MainImg
		{
			get
			{
				return this._MainImg;
			}
			set
			{
				if ((this._MainImg != value))
				{
					this.OnMainImgChanging(value);
					this.SendPropertyChanging();
					this._MainImg = value;
					this.SendPropertyChanged("MainImg");
					this.OnMainImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayMainImgAsIs", DbType="Bit")]
		public System.Nullable<bool> DisplayMainImgAsIs
		{
			get
			{
				return this._DisplayMainImgAsIs;
			}
			set
			{
				if ((this._DisplayMainImgAsIs != value))
				{
					this.OnDisplayMainImgAsIsChanging(value);
					this.SendPropertyChanging();
					this._DisplayMainImgAsIs = value;
					this.SendPropertyChanged("DisplayMainImgAsIs");
					this.OnDisplayMainImgAsIsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainImgCaption", DbType="NVarChar(50)")]
		public string MainImgCaption
		{
			get
			{
				return this._MainImgCaption;
			}
			set
			{
				if ((this._MainImgCaption != value))
				{
					this.OnMainImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._MainImgCaption = value;
					this.SendPropertyChanged("MainImgCaption");
					this.OnMainImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayMainImgCaption", DbType="Bit")]
		public System.Nullable<bool> DisplayMainImgCaption
		{
			get
			{
				return this._DisplayMainImgCaption;
			}
			set
			{
				if ((this._DisplayMainImgCaption != value))
				{
					this.OnDisplayMainImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._DisplayMainImgCaption = value;
					this.SendPropertyChanged("DisplayMainImgCaption");
					this.OnDisplayMainImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoMainImgCaption", DbType="Bit")]
		public System.Nullable<bool> AutoMainImgCaption
		{
			get
			{
				return this._AutoMainImgCaption;
			}
			set
			{
				if ((this._AutoMainImgCaption != value))
				{
					this.OnAutoMainImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._AutoMainImgCaption = value;
					this.SendPropertyChanged("AutoMainImgCaption");
					this.OnAutoMainImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainImgSmall", DbType="NVarChar(100)")]
		public string MainImgSmall
		{
			get
			{
				return this._MainImgSmall;
			}
			set
			{
				if ((this._MainImgSmall != value))
				{
					this.OnMainImgSmallChanging(value);
					this.SendPropertyChanging();
					this._MainImgSmall = value;
					this.SendPropertyChanged("MainImgSmall");
					this.OnMainImgSmallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListImgCaption", DbType="NVarChar(50)")]
		public string ListImgCaption
		{
			get
			{
				return this._ListImgCaption;
			}
			set
			{
				if ((this._ListImgCaption != value))
				{
					this.OnListImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._ListImgCaption = value;
					this.SendPropertyChanged("ListImgCaption");
					this.OnListImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayListImgAsIs", DbType="Bit")]
		public System.Nullable<bool> DisplayListImgAsIs
		{
			get
			{
				return this._DisplayListImgAsIs;
			}
			set
			{
				if ((this._DisplayListImgAsIs != value))
				{
					this.OnDisplayListImgAsIsChanging(value);
					this.SendPropertyChanging();
					this._DisplayListImgAsIs = value;
					this.SendPropertyChanged("DisplayListImgAsIs");
					this.OnDisplayListImgAsIsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateMainImgSmall", DbType="Bit")]
		public System.Nullable<bool> CreateMainImgSmall
		{
			get
			{
				return this._CreateMainImgSmall;
			}
			set
			{
				if ((this._CreateMainImgSmall != value))
				{
					this.OnCreateMainImgSmallChanging(value);
					this.SendPropertyChanging();
					this._CreateMainImgSmall = value;
					this.SendPropertyChanged("CreateMainImgSmall");
					this.OnCreateMainImgSmallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoListImgCaption", DbType="Bit")]
		public System.Nullable<bool> AutoListImgCaption
		{
			get
			{
				return this._AutoListImgCaption;
			}
			set
			{
				if ((this._AutoListImgCaption != value))
				{
					this.OnAutoListImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._AutoListImgCaption = value;
					this.SendPropertyChanged("AutoListImgCaption");
					this.OnAutoListImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayListImgCaption", DbType="Bit")]
		public System.Nullable<bool> DisplayListImgCaption
		{
			get
			{
				return this._DisplayListImgCaption;
			}
			set
			{
				if ((this._DisplayListImgCaption != value))
				{
					this.OnDisplayListImgCaptionChanging(value);
					this.SendPropertyChanging();
					this._DisplayListImgCaption = value;
					this.SendPropertyChanged("DisplayListImgCaption");
					this.OnDisplayListImgCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DisplayDate
		{
			get
			{
				return this._DisplayDate;
			}
			set
			{
				if ((this._DisplayDate != value))
				{
					this.OnDisplayDateChanging(value);
					this.SendPropertyChanging();
					this._DisplayDate = value;
					this.SendPropertyChanged("DisplayDate");
					this.OnDisplayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DisplayEndDate
		{
			get
			{
				return this._DisplayEndDate;
			}
			set
			{
				if ((this._DisplayEndDate != value))
				{
					this.OnDisplayEndDateChanging(value);
					this.SendPropertyChanging();
					this._DisplayEndDate = value;
					this.SendPropertyChanged("DisplayEndDate");
					this.OnDisplayEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="Int")]
		public System.Nullable<int> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleInH1Tag", DbType="Bit")]
		public System.Nullable<bool> TitleInH1Tag
		{
			get
			{
				return this._TitleInH1Tag;
			}
			set
			{
				if ((this._TitleInH1Tag != value))
				{
					this.OnTitleInH1TagChanging(value);
					this.SendPropertyChanging();
					this._TitleInH1Tag = value;
					this.SendPropertyChanged("TitleInH1Tag");
					this.OnTitleInH1TagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogNumber", DbType="NVarChar(20)")]
		public string CatalogNumber
		{
			get
			{
				return this._CatalogNumber;
			}
			set
			{
				if ((this._CatalogNumber != value))
				{
					this.OnCatalogNumberChanging(value);
					this.SendPropertyChanging();
					this._CatalogNumber = value;
					this.SendPropertyChanged("CatalogNumber");
					this.OnCatalogNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dbsArticles_dbsCategories")]
	public partial class dbsArticles_dbsCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ArticleID;
		
		private int _HorizontalCatID;
		
		private System.Nullable<int> _OrderNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArticleIDChanging(int value);
    partial void OnArticleIDChanged();
    partial void OnHorizontalCatIDChanging(int value);
    partial void OnHorizontalCatIDChanged();
    partial void OnOrderNoChanging(System.Nullable<int> value);
    partial void OnOrderNoChanged();
    #endregion
		
		public dbsArticles_dbsCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ArticleID
		{
			get
			{
				return this._ArticleID;
			}
			set
			{
				if ((this._ArticleID != value))
				{
					this.OnArticleIDChanging(value);
					this.SendPropertyChanging();
					this._ArticleID = value;
					this.SendPropertyChanged("ArticleID");
					this.OnArticleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorizontalCatID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HorizontalCatID
		{
			get
			{
				return this._HorizontalCatID;
			}
			set
			{
				if ((this._HorizontalCatID != value))
				{
					this.OnHorizontalCatIDChanging(value);
					this.SendPropertyChanging();
					this._HorizontalCatID = value;
					this.SendPropertyChanged("HorizontalCatID");
					this.OnHorizontalCatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="Int")]
		public System.Nullable<int> OrderNo
		{
			get
			{
				return this._OrderNo;
			}
			set
			{
				if ((this._OrderNo != value))
				{
					this.OnOrderNoChanging(value);
					this.SendPropertyChanging();
					this._OrderNo = value;
					this.SendPropertyChanged("OrderNo");
					this.OnOrderNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
