//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbstractPages
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Layout { get; set; }
        public int Order { get; set; }
        public bool Visible { get; set; }
        public bool ShowInMenu { get; set; }
        public bool ShowInSitemap { get; set; }
        public bool ShowInAdminMenu { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public string SeoUrlName { get; set; }
        public string SeoTitle { get; set; }
        public string SeoH1 { get; set; }
        public string SeoInLinkName { get; set; }
        public string SeoKywords { get; set; }
        public string SeoDescription { get; set; }
        public string PermissionsView { get; set; }
        public string PermissionsEdit { get; set; }
        public bool PermissionsUpdateChildPages { get; set; }
        public string RedirectTo { get; set; }
        public int ParentID { get; set; }
        public string RouteUrl { get; set; }
        public string PageName { get; set; }
        public string PageIcon { get; set; }
        public string LanguageCode { get; set; }
        public string ShortDescription { get; set; }
        public string Pic { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string XML1 { get; set; }
        public string XML2 { get; set; }
        public int DomainID { get; set; }
        public string RoleDefault { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> ExtendedFrom { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameCsv { get; set; }
        public string EnglishNameForCertificate { get; set; }
        public string InsuranceMaxMoney { get; set; }
        public string DaysCsv { get; set; }
        public Nullable<int> CardProgram { get; set; }
        public Nullable<bool> ShopShowInMainPage { get; set; }
        public Nullable<bool> ShopShowInMainPage1 { get; set; }
        public string ShopBanner { get; set; }
        public Nullable<bool> ShopShowInMainPage2 { get; set; }
        public Nullable<bool> ShopShowInBest { get; set; }
        public Nullable<bool> ShopIsVisibleOnMirror { get; set; }
        public Nullable<bool> ShopShowInSale { get; set; }
        public Nullable<bool> ShopShowInStock { get; set; }
        public Nullable<decimal> ShopPrice { get; set; }
        public Nullable<decimal> ShopOldPrice { get; set; }
        public Nullable<decimal> ShopAddShippingPrice { get; set; }
        public Nullable<bool> ShopAddShippingPriceEach { get; set; }
        public string ShopPtoductID { get; set; }
        public string ShopBrand { get; set; }
        public string ShopTags { get; set; }
        public string ShopRelatedProducts { get; set; }
        public string ShopCategoryNames { get; set; }
        public string ShopCategoryIDs { get; set; }
        public string ShopVideoGallery { get; set; }
        public Nullable<bool> ShopImported { get; set; }
        public string PageTemplate { get; set; }
        public bool ShowInHomePage { get; set; }
        public string RelatedArticles { get; set; }
        public string Author { get; set; }
        public string Photographer { get; set; }
        public Nullable<int> MigrationOldID { get; set; }
        public string Author1 { get; set; }
        public bool HideComment { get; set; }
        public string MainImg { get; set; }
    }
}
