//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banners
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Title { get; set; }
        public bool ShowForAll { get; set; }
        public string BannerGroup { get; set; }
        public int Clicks { get; set; }
        public string LangCode { get; set; }
        public System.DateTime ShowDateMax { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Type { get; set; }
        public string MainFile { get; set; }
        public string OtherFile { get; set; }
        public string Link { get; set; }
        public string Html { get; set; }
        public string Text { get; set; }
    }
}
