//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeBanners
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public int Order { get; set; }
        public string Pic { get; set; }
    }
}
