//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletters
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public System.DateTime NewsletterDate { get; set; }
        public string NewsletterName { get; set; }
        public string NewsletterEmail { get; set; }
        public string NewsletterData { get; set; }
        public string RoleDefault { get; set; }
        public string NewsletterIdNumber { get; set; }
        public bool NewsletterAccept { get; set; }
    }
}
