//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutEmails
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string MailTo { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime LastTry { get; set; }
        public int TimesSent { get; set; }
    }
}
