//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int ID { get; set; }
        public string AdminEmail { get; set; }
        public string HeaderHtml { get; set; }
        public string FotterHtml { get; set; }
        public int DomainPageID { get; set; }
        public bool LanguageRTL { get; set; }
        public string LanguageCode { get; set; }
        public string Domain { get; set; }
        public string Themes { get; set; }
        public string Error404 { get; set; }
        public string Roles { get; set; }
        public string DivingRank { get; set; }
        public int MinimumAge { get; set; }
        public int MaximumAge { get; set; }
        public string PaymentCreditGuardID1 { get; set; }
        public string PaymentCreditGuardID2 { get; set; }
        public string PaymentCreditGuardID3 { get; set; }
        public string PaymentCreditGuardID4 { get; set; }
        public string PaymentCreditGuardUrl { get; set; }
        public string SmsUsername { get; set; }
        public string SmsPassword { get; set; }
        public string SmsDisplaySender { get; set; }
        public string SmsText { get; set; }
        public string ShopSiteMainCollors { get; set; }
        public bool ShopPaymentUse { get; set; }
        public bool ShopPaymentPhoneUse { get; set; }
        public bool ShopPaymentInstoreUse { get; set; }
        public bool ShopPaymentPayPalUse { get; set; }
        public string ShopPaymentPayPalEmail { get; set; }
        public bool ShopPaymentCreditGuardUse { get; set; }
        public string ShopPaymentCreditGuardUser { get; set; }
        public string ShopPaymentCreditGuardPass { get; set; }
        public string ShopPaymentCreditGuardMod { get; set; }
        public string ShopPaymentCreditGuardMod2 { get; set; }
        public bool ShopPaymentZCreditUse { get; set; }
        public string ShopPaymentZCreditTerminalNumber { get; set; }
        public string ShopPaymentZCreditUserName { get; set; }
        public bool ShopShippingUse { get; set; }
        public bool ShopShippingSelfUse { get; set; }
        public string ShopShippingSelfText { get; set; }
        public decimal ShopShippingPrice { get; set; }
        public int ShopShippingDays { get; set; }
        public string ShopShippingName { get; set; }
        public string ShopShippingText { get; set; }
        public bool ShopInvoiceUse { get; set; }
        public string ShopInvoiceUser { get; set; }
        public string ShopInvoiceKey { get; set; }
        public string TaksPercent { get; set; }
        public string MenuGroups { get; set; }
    }
}
