//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopAnaliticsDatas
    {
        public int ID { get; set; }
        public System.DateTime ShopDate { get; set; }
        public int ShopUnic { get; set; }
        public int ShopShow { get; set; }
        public int ShopPhone { get; set; }
        public int ShopContact { get; set; }
        public int ShopBuy { get; set; }
        public string ShopReferalUrl { get; set; }
        public string ShopReferalSearch { get; set; }
        public int ShopPageID { get; set; }
        public string ShopPageTitle { get; set; }
        public string ShopPageRouteUrl { get; set; }
        public int ShopDomainID { get; set; }
    }
}
