//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrders
    {
        public int ID { get; set; }
        public int ShopStatus { get; set; }
        public string ShopFirstName { get; set; }
        public string ShopLastName { get; set; }
        public string ShopCompanyName { get; set; }
        public string ShopPhone1 { get; set; }
        public string ShopPhone2 { get; set; }
        public string ShopEmail { get; set; }
        public string ShopAdressStreet { get; set; }
        public string ShopAdressCity { get; set; }
        public string ShopOther { get; set; }
        public int ShopPayType { get; set; }
        public decimal ShopTotal { get; set; }
        public string ShopApprovedToken { get; set; }
        public string ShopApprovedGuid { get; set; }
        public System.DateTime ShopApprovedDate { get; set; }
        public bool ShopInvoiceSent { get; set; }
        public string ShopInvoiceID { get; set; }
        public string ShopInvoiceURL { get; set; }
        public int ShopShippingType { get; set; }
        public decimal ShopShippingPrice { get; set; }
        public System.DateTime ShopDeliveryDate { get; set; }
        public string ShopLog { get; set; }
        public string ShopXML { get; set; }
        public int ShopDomainID { get; set; }
    }
}
