//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopProductOptions
    {
        public int ID { get; set; }
        public int ShopParentID { get; set; }
        public int ShopOrder { get; set; }
        public string ShopTitle { get; set; }
        public int ShopProductOptionTypeValue { get; set; }
        public string ShopXML { get; set; }
        public int ShopDomainID { get; set; }
    }
}
