//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMigration.NewDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInsurances
    {
        public int ID { get; set; }
        public int TravelInsuranceID { get; set; }
        public string IdNumber { get; set; }
        public string UserFname { get; set; }
        public string UserLname { get; set; }
        public string UserFnameEng { get; set; }
        public string UserLnameEng { get; set; }
        public string CustomerAddress { get; set; }
        public string City { get; set; }
        public int AgentID { get; set; }
        public int SumForPay { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public bool IsCleared { get; set; }
        public System.DateTime InsuranceDate { get; set; }
        public int TravelInsurancePeriods { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string HealthCare { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string Beneficiaries { get; set; }
        public string AutorizationNum { get; set; }
        public bool IsToCard { get; set; }
        public bool ToDelete { get; set; }
        public string Parametr { get; set; }
        public string NotifyInfo { get; set; }
        public int Type { get; set; }
        public string Log { get; set; }
        public int Days { get; set; }
        public System.Guid OrderGuid { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayError { get; set; }
        public int Gender { get; set; }
        public string CreditGuardTxId { get; set; }
        public bool SentNotification5MinutesNoPay { get; set; }
        public bool SentNotificationAnnual2weeksBefore { get; set; }
        public bool SentNotificationAnnual5DaysBefore { get; set; }
        public string CoverPrice { get; set; }
        public Nullable<System.DateTime> CardDate { get; set; }
    }
}
